# Decision tree

From [Source1](https://www.saedsayad.com/decision_tree.htm)

Decision tree builds classification or regression models in the form of a tree structure. It breaks down a dataset into smaller and smaller subsets while at the same time an associated decision tree is incrementally developed

The core algorithm for building decision trees called ID3 by J. R. Quinlan which employs a top-down, greedy search through the space of possible branches with no backtracking.

ID3 uses Entropy and Information Gain to construct a decision tree.



## Information gain

A decision tree is built top-down from a root node and involves partitioning the data into subsets that contain instances with similar values (homogenous). ID3 algorithm uses entropy to calculate the homogeneity of a sample. If the sample is completely homogeneous the entropy is zero and if the sample is an equally divided it has entropy of one.

Information gain (IG) measures how much "information" a feature gives us about the class.

- Features that perfectly partition should give maximal information.
- Unrelated features should give no information.

Suppose we want to split on the first variable (𝑥1):

If we split at $x_1 < 3.5$ , we get an optimal split
I we split at $ x_1 < 4$, wz make a mistake

- Idea: A better split should make the samples “pure” (homogeneous).

Impurity/Entropy (informal)

- Measures the level of impurity in a group of examples

![Example impurtiy](https://dynalist.io/u/Wd8A6pPKQ-7L1FuYDVEsnR0J)

### Measures for Selecting the Best Split

- Impurity measures include:

$$\text { Entropy }=-\sum_{i=1}^{K} p_{k} \log _{2} p_{k}$$
$$\text { Gini }=1-\sum_{i=1}^{K} p_{k}^{2}$$
$$\text { Classification error }=1-\max _{i} p_{\text { en }}$$

![Entropy](https://dynalist.io/u/COM8fPj_0f1SY6j0LTbhLmNb)

- 16/30 are green circles; 
- 14/30 are pink crosses
  - log2(16/30) = -.9; log2(14/30) = -1.1
- Entropy = -(16/30)(-.9) –(14/30)(-1.1) = .99 

- Entropy comes from information theory. The higher the entropy the more the information content.
  - Information gain tells us how important a given attribute of the feature vectors is
  - We will use it to decide the ordering of attributesin the nodes of a decision tree.
- the change in entropy, or Information Gain, is defined as: 

$$\Delta H=H-\frac{m_{L}}{m} H_{L}-\frac{m_{R}}{m} H_{R}$$

where $𝑚$ is the total number of instances, with $𝑚_𝑘$ instances belonging to class $𝑘$, where $𝐾 = 1, … , 𝑘.$

$$\text { Information Gain }=\quad \text { entropy (parent) }-[\text { average entropy (children) }]$$

**Example**

The column `Play` is the parent column and the remaining columns are the childs

- 5 No
- 9 Yes

|  Outlook | Temperature | Humidity | Windy | Play |
| -------- | ----------- | -------- | ----- | ---- |
| Sunny    | Hot         | High     | False | No   |
| Sunny    | Hot         | High     | True  | No   |
| Overcast | Hot         | High     | False | Yes  |
| Rainy    | Mild        | High     | False | Yes  |
| Rainy    | Cool        | Normal   | False | Yes  |
| Rainy    | Cool        | Normal   | True  | No   |
| Overcast | Cool        | Normal   | True  | Yes  |
| Sunny    | Mild        | High     | False | No   |
| Sunny    | Cool        | Normal   | False | Yes  |
| Rainy    | Mild        | Normal   | False | Yes  |
| Sunny    | Mild        | Normal   | True  | Yes  |
| Overcast | Mild        | High     | True  | Yes  |
| Overcast | Hot         | Normal   | False | Yes  |
| Rainy    | Mild        | High     | True  | No   |
|          |             |          |       |      |


#### Parent 

$$\begin{aligned} & \mathrm{H}(Y)=-\sum_{i=1}^{K} p_{k} \log _{2} p_{k} \\=&-\frac{5}{14} \log _{2} \frac{5}{14}-\frac{9}{14} \log _{2} \frac{9}{14} \\=& 0.94 \end{aligned}$$

#### Childs

**Humidity**

There are 7 high and 7 normal. We use the parent computation $H(Y)$ and substract to the information gain from `Humidity`

$$\begin{array}{l}{\text {InfoGain}(\text { Humidity })=} \\ {H(Y)-\frac{m_{L}}{m} H_{L}-\frac{m_{R}}{m} H_{R}} \\ {=0.94-\frac{7}{14} H_{L}-\frac{7}{14} H_{R}}\end{array}$$

Now we need to compute $H_L$ using the entropy formula. Among the 7 `Normal` label, 6 belongs to `Yes` and 1 to  `No`

$$\begin{array}{c}{\text {InfoGain}(\text { Humidity })=} \\ {\quad H(Y)-\frac{m_{L}}{m} H_{L}-\frac{m_{R}}{m} H_{R}} \\ {0.94-\frac{7}{14} H_{L}-\frac{7}{14} H_{R}} \\ {H_{L}=-\frac{6}{7} \log _{2} \frac{6}{7}-\frac{1}{7} \log _{2} \frac{1}{7}}\end{array}$$

We repeat the same exercice for $H_R$

$$H_{R}=-\frac{3}{7} \log _{2} \frac{3}{7}-\frac{4}{7} \log _{2} \frac{4}{7}$$

All together, we get:

$$\begin{array}{l}{\text {InfoGain}(\text { Humidity })=} \\ {H(Y)-\frac{m_{L}}{m} H_{L}-\frac{m_{R}}{m} H_{R}} \\ {0.94-\frac{7}{14} 0.592-\frac{7}{14} 0.985} \\ {=0.94-0.296-0.4925} \\ {=0.1515}\end{array}$$

We compute the information gain for each feature

-  Information gain for each feature:
  -  Outlook = 0.247
  - Temperature = 0.029
  -  Humidity = 0.152
  - Windy = 0.048
  
 - Initial split is on outlook, because it is the feature with the highest information gain. 
 -  In the next step, we look for the second best split:
  - Temperature: .571
  - Windy: .020
  - Humidity: .971
  
  The seconds winner are Temperature and Humidity
 








In [0]:
import numpy as np

In [0]:
def entropy(p):
  """
  Define entropy. 
  """
  
  d_entropy = p * np.log2(p)
  
  return d_entropy

In [3]:
entropy(0.3)

-0.5210896782498619

### Define information gain

[Source](https://www.python-course.eu/Decision_Trees.php)

Entropy defines the impurity of the feature. 

our task is to find the best feature in terms of information gain (Remember that we want to find the feature which splits the data most accurate along the target feature values) which we should use to first split our data on (which serves as root node)

how can we check which of the descriptive features most accurately splits the dataset, that is, remains the dataset with the lowest impurity ≈ entropy or in other words best classifies the target features by its own

we use each descriptive feature and split the dataset along the values of these descriptive feature and then calculate the entropy of the dataset once we have split the data along the feature values. This gives us the remaining entropy after we have split the dataset along the feature values.

$$
\text {InfoGain}\left(\text {feature}_{d}\right)=\text {Entropy}(D)-\text {Entropy (featured} )
$$

$$InforGain(feature_{d},D) = Entropy(D)-\sum_{t \ \in \ feature}(\frac{|feature_{d} = t|}{|D|}*H(feature_{d} = t))$$

$$Entropy(D)-\sum_{t \ \in \ feature}(\frac{|feature_{d} = t|}{|D|}*(-\sum_{k \ \in \ target}(P(target=k,feature_{d} = t)*log_{2}(P(target = k,feature_{d} = t))))$$

For each column, we end up with $k$ * $n$ "entropy" computation, where $k$  is the class of the column to predict and $n$ the number of class in the feature. 

If the column to predict has 2 classes and the feature column has 2 class as well, we end up adding 4 $H(feature)$ together on top of the $H(Y)$


In [0]:
import pandas as pd

Outlook = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
           'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy'
          ]
Temperature = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild',
               'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
Humidity = ['High', 'High', 'High' ,'High', 'Normal', 'Normal', 'Normal',
            'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal',
            'High']
Windy = [False, True, False, False, False, True, True, False, False, False,
        True, True, False, True]
Play = ['No', 'No','Yes', 'Yes', 'Yes', 'No', 'Yes', 'No',
        'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']

df_test = pd.DataFrame( {'Outlook': Outlook, 'Temperature': Temperature,
               'Humidity': Humidity, 'Windy': Windy, 'Play':Play})
df_test

In [5]:
import pandas as pd
#df_test.iloc[:, :-1].apply(entropy)
data = pd.DataFrame({"toothed":["True","True","True","False","True","True","True","True","True","False"],
                     "breathes":["True","True","True","True","True","True","False","True","True","True"],
                     "legs":["Between","Between","False","Between","True","True","Between","False","True","True"],
                     "species":["Mammal","Mammal","Reptile","Mammal","Mammal","Mammal","Reptile","Reptile","Mammal","Reptile"]}, 
                    columns=["toothed","breathes","legs","species"])
features = data[["toothed","breathes","legs"]]
target = data["species"]
data

toothed breathes     legs  species
0    True     True  Between   Mammal
1    True     True  Between   Mammal
2    True     True    False  Reptile
3   False     True  Between   Mammal
4    True     True     True   Mammal
5    True     True     True   Mammal
6    True    False  Between  Reptile
7    True     True    False  Reptile
8    True     True     True   Mammal
9   False     True     True  Reptile

In [0]:
def informationGains(features, y):
  """
  Define information gains.
  
  Pass a pandas Dataframe and compute information gain
  column wise
  """
  
  ### List features
  
  list_f = []
  
  ### List Gain information
  
  list_gain = []
  
  ### Name target column 
  target_name = y.name
  
  ### Compute Entropy Y
  
  feature_class_y = y.value_counts(normalize=True)
  entropy_Y = np.abs(feature_class_y.apply(entropy).sum())
  
  ### Concat target and features
  df_concat = pd.concat([features, y], axis = 1)
 
  
  for col in features.columns:
  ### Compute count by feature class
    feature_class = df_concat.groupby([col, target_name]).agg({col: 'count'})
  
  ### Compute the share within each class of the label feature
    within_feature_class = feature_class.groupby(level=0).apply(
      lambda x: x / float(x.sum()))
  
  ### Compute the share between each class of the label feature
    between_feature_class = feature_class.groupby(level=0).agg({col: 'sum'})
    between_feature_class = between_feature_class.apply(
      lambda x: x / float(x.sum()))
  
    df_unstack = within_feature_class.unstack()
    df_unstack = df_unstack.fillna(0)
    within_entropy = df_unstack.apply(entropy, axis = 1)
    within_entropy = within_entropy.fillna(0)
  ### compute sum within share class
    sum_entropy_class = within_entropy.apply(sum, axis= 1)
  
  ### Compute dot product share between with sum share within
    gain_information = entropy_Y - \
    np.abs(np.dot(sum_entropy_class, between_feature_class))
    
    list_f.append([col])
    list_gain.append(gain_information)
    
  max_gain =  np.max(list_gain)
  max_feature = list_f[list_gain.index(max_gain)]

  ### Prepare dataset for next split
  
  label_winner = df_concat[max_feature[0]].unique()
  
  #### Get stop if target is purely separeted
  
  ##### Need to store the new dataframe for the next leaf
  l_new_df_features = []
  l_new_df_label = []
  l_new_class = []
   
  for label_ in label_winner:
    
    is_winner = df_concat[df_concat[max_feature[0]] ==
                    label_].iloc[:, -1].unique()
    if len(is_winner) == 1:
  
  ### Done splitting
      winner_split  = label_
      target_label = is_winner[0]
    else:
  ### Get next dataframe
      new_df_features = df_concat[df_concat[max_feature[0]] ==
                    label_].iloc[:,:-1].drop(columns = max_feature[0])
      new_df_label = df_concat[df_concat[max_feature[0]] ==
                    label_].iloc[:,-1]
      
      l_new_df_features.append(new_df_features)
      l_new_df_label.append(new_df_label)
      l_new_class.append(label_)
      
      
  try:
    winner_split
  except:
    winner_split = None
    target_label = None
  
  #### Need to review results: Should match the parent node
  df_gain = {
        'features' : list_f,
        'gain_information' : list_gain,
        'winner': {
            'feature':max_feature,
            'gain_information': max_gain,
            'label': winner_split,
            'label_target':target_label
        },
      'next_split': {
          'features': {
              'class':l_new_class,
              'df': l_new_df_features,
          'target': l_new_df_label
          }
      }
        
    }
  
  return df_gain

In [104]:
test = informationGains(features = features, y= target)
test['winner']['label']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log2
  


'False'

In [99]:
for key, value in enumerate(test['next_split']['features']['class']):
  print(value)

Between
True


Hence the splitting the dataset along the feature legs results in the largest information gain and we should use this feature for our root node.

We see that for legs == False, the target feature values of the remaining dataset are all Reptile and hence we set this as leaf node because we have a pure dataset (Further splitting the dataset on any of the remaining two features would not lead to a different or more accurate result since whatever we do after this point, the prediction will remain Reptile). 

Additionally, you see that the feature legs is no longer included in the remaining datasets. Because we already has used this (categorical) feature to split the dataset on it must not be further used.


In [0]:
def build_tree(features, target):
  """
  Build decision tree.
  
  Loop until no more column
  """

  l_nodes = []
  l_features = []
  l_stops = []
  l_gaininfo = []
  l_target_winner = []
 
  
  #### Set first pass
  features_ = [features]
  target_ = [target]
 
  #### there are two loops: 
  ##### First, we loop over the dataframes
  ##### Second, we loop over the columns
  ##### Each loop will give us one branch and leaves of the tree
  i = 0
  while len(features_) > 0:
    for n, df in enumerate(features_):
      
      #n_col = len(df.columns) 
    #for i in range(0, n_col):
      print(i, n)
      df_ = informationGains(features = df, y = target_[n])
      
      print(df_['winner']['feature'], df_['winner']['label'])
      for key, value in enumerate(df_['next_split']['features']['class']):
        print(value)
    #print(df_['next_split']['features']['class'][n])
      
  
      #### Store the results 
      #l_nodes.append(1)
      #l_features.append(df_['winner']['feature'])
      #l_stops.append(df_['winner']['label'])
      #l_gaininfo.append(df_['winner']['gain_information'])
      #l_target_winner.append(df_['winner']['label_target'])
  
    features_ = df_['next_split']['features']['df']
    target_ = df_['next_split']['features']['target']
    i=+1
  dic_tree = {
    'node': l_nodes,
    'feature': l_features,
    'stop': l_stops,
    'gain_information': l_gaininfo,
    'label_target': l_target_winner,
    
    }
  return dic_tree

In [110]:
features_ = features
target_ = target
test = build_tree(features = features_, target = target_)

0 0
['legs'] False
Between
True
1 0
['breathes'] False
1 1
['toothed'] False


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log2
  


In [0]:
list_ = ['False', 'Between', 'True']

dic_test ={}

dic_test.update({'legs' : {'False'}})

In [123]:
dic_test

{'legs': {'Between'}}

In [0]:
dic_test.update({'legs' : {'Between'}})

Mind the last split (node) where the dataset got split on the breathes feature. Here the breathes feature solely contains data where breaths == True. Hence for breathes == False there are no instances in the dataset and therewith there is no sub-Dataset which can be built. In that case we return the most frequently occurring target feature value in the original dataset which is Mammal. This is an example how our tree model generalizes behind the training data.

If we consider the other branch, that is breathes == True we know, that after splitting the Dataset on the values of a specific feature (breathes {True,False}) in our case, the feature must be removed. Well, that leads to a dataset where no more features are available to further split the dataset on. Hence we stop growing the tree and return the mode value of the direct parent node which is "Mammal"

# ID3 Algorithm

That leads us to the introduction of the ID3 algorithm which is a popular algorithm to grow decision trees, published by Ross Quinlan in 1986. Besides the ID3 algorithm there are also other popular algorithms like the C4.5, the C5.0 and the CART algorithm which we will not further consider here. Before we introduce the ID3 algorithm lets quickly come back to the stopping criteria of the above grown tree.

There are mainly three useful cases in which we stop the tree from growing assuming we do not stop it beforehand by defining for instance a maximum tree depth or a minimum information gain value. 

We stop the tree from growing when:

1. All rows in the target feature have the same value 
2. The dataset can be no longer split since there are no more features left
3. The dataset can no longer be split since there are no more rows left / There is no data left

By definition, we say that if the growing gets stopped because of stopping criteria two, the leaf node should predict the most frequently occurring target feature value of the superior (parent) node. If the growing gets stopped because of the third stopping criteria, we assign the leaf node the mode target feature value of the original dataset.

## Example

Since we now know the principal steps of the ID3 algorithm, we will start create our own decision tree classification model from scratch in Python.

Therefore we will use the whole UCI Zoo Data Set.
This dataset consists of 101 rows and 17 categorically valued attributes defining whether an animal has a specific property or not (e.g.hairs, feathers,..). The first attribute represents the name of the animal and will be removed. The target feature consist of 7 integer values [1 to 7] which represents [1:Mammal, 2:Bird, 3:Reptile, 4:Fish, 5:Amphibian, 6:Bug, 7:Invertebrate]

That said, there are four important steps:

1. The calculation of the Information Gain
2. The recursive call of the TreeModel
3. The building of the actual tree structure
4. The species prediction of a new unseen animal-instance

Here the most critical aspects are the recursive call of the TreeModel, the creation of the tree itself (building the tree structure) as well as the prediction of a unseen query instance (the process of wandering down the tree to predict the class of a unseen query instance).

In [0]:
dataset=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data',
           names=['animal_name','hair','feathers','eggs','milk',
                  'airbone','aquatic','predator','toothed','backbone',
                  'breathes','venomous','fins','legs','tail','domestic',
                  'catsize','class'])
dataset=dataset.drop('animal_name',axis=1)
dataset.head()

hair  feathers  eggs  milk  airbone  ...  legs  tail  domestic  catsize  class
0     1         0     0     1        0  ...     4     0         0        1      1
1     1         0     0     1        0  ...     4     1         0        1      1
2     0         0     1     0        0  ...     0     1         0        0      4
3     1         0     0     1        0  ...     4     0         0        1      1
4     1         0     0     1        0  ...     4     1         0        1      1

[5 rows x 17 columns]

We run the algorithm until no more rows in the features. 

First of all, let's try the algorithm without train/test split

In [0]:
X = dataset.iloc[:, :-1]
Y = dataset.iloc[:, -1]

In [0]:
informationGains(features = X, y = Y)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log2
  


{'features': [['hair'],
  ['feathers'],
  ['eggs'],
  ['milk'],
  ['airbone'],
  ['aquatic'],
  ['predator'],
  ['toothed'],
  ['backbone'],
  ['breathes'],
  ['venomous'],
  ['fins'],
  ['legs'],
  ['tail'],
  ['domestic'],
  ['catsize']],
 'gain_information': [array([0.79067457]),
  array([0.71794998]),
  array([0.83013845]),
  array([0.97431972]),
  array([0.46970261]),
  array([0.38948748]),
  array([0.09344704]),
  array([0.86569415]),
  array([0.67616274]),
  array([0.61449403]),
  array([0.13308963]),
  array([0.46661357]),
  array([1.3630469]),
  array([0.50046045]),
  array([0.05066878]),
  array([0.30849034])],
 'next_split': {'features':     hair  feathers  eggs  milk  ...  fins  tail  domestic  catsize
  15     0         0     1     0  ...     0     0         0        0
  24     0         0     1     0  ...     0     0         0        0
  30     0         0     1     0  ...     0     0         0        0
  39     1         0     1     0  ...     0     0         1        0


In [0]:
build_tree(features = X, target = Y)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log2
  


UnboundLocalError: ignored