# Introduction

The NumPy package (forNumerical Python) is one of the most used packages for calculation in Python (and therefore in the development of pricers). NumPy results from the unification of the Numeric and Numarray libraries in the mid-2000s, and is the basis of SciPy, set of Python libraries oriented scientific computing (including iPython, Pandas, Matplotlib, Scipy ...).

Indeed, NumPy offers many advantages:

- The type of ndarray object making it possible to store in memory N-dimensional arrays ( with N = 1, matrices with N = 2 ...) efficiently (contiguous blocks of memory with homogeneous data type)

- Algorithms and functions (many of which are written in C) to work quickly with

whole arrays in a vectorial way (ie without using a loop)

- the generation of random numbers

This allows Python to compete with lower-level performance languages ​​-

NumPy-based programs are typically 10 to 100 times faster than pure written equivalents

Python. NumPy is therefore an essential tool for optimizing Python code.

This module is based on Chapter 4 of ExcelPython for Data Analysis (2nd Ed., O'Reilly, 2017)

Wes McKinney (who is none other than the creator of the Python Pandas package widely used in data
science, especially for time-series). Notebook corresponding to the chapter in question is available on GitHub.

As we have seen, it is necessary to import a package before you can use it. It is customary to import NumPy via:

In [6]:
import numpy as np

To give you an idea of ​​the performance gain, let's take the example of an object containing a million whole and want to square:

# NumPy arrays

An array is a type of multi-dimensional generic container for storing data

homogeneous (ie of the same type).

If it is possible to use strings in NumPy arrays, its strength is elsewhere and so it is rather recommend using the Pandas library for data structures that include non-numeric data.

The main attributes of an array are:

- its shape (oushape), a tuple indicating the size of each dimension 
- its number of dimensions (ndim)
- its size (ousize), ie the total number of elements contained in the array (all dimensions combined)
- its type, an object describing the data type of the array

### Creating from a list

A first way to create arrays is to convert a Python object, like a list, into an array:


In [3]:
my_list = range ( 0 , 10 )
my_list

range(0, 10)

In [7]:
my_arr = np.array(my_list)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_arr.shape # attention, no parentheses because shape, ndim, size

(10,)

In [9]:
 my_arr.ndim

1

In [10]:
 my_arr.size # equivalent to np.product (my_arr.shape)

10

In [11]:
 my_arr.dtype

dtype('int64')

### Creating from a list of lists

We can also convert a list of lists (of the same size) into a multidimensional array:

In [12]:
my_list2 = range ( 0 , 100 , 10 )
my_arr = np.array ([my_list, my_list2])

In [22]:
# Creation of a function to display the shape, ndim, size and dtype of an array
def summarray (arr):
    shape = arr.shape
    ndim = arr.ndim
    size = arr.size
    dtype = arr.dtype
    print ("The array has {} dimension (s), its shape is {} ,\n \
           its size is{} (ie it contains {} elements in total) and its \n \
           dtype is {}.".format (ndim, shape, size, size, dtype))
summarray (my_arr)

The array has 2 dimension (s), its shape is (3, 3) ,
            its size is9 (ie it contains 9 elements in total) and its 
            dtype is int64.


In the case of a matrix, the first number returned byshape (ie the first dimension) is the number of lines (ourows, axis = 0) and the second number (ie the second dimension) is the number of columns (columns, ieaxis = 1).

### Creating from explicit values

Let's now create an array from explicit values ​​- first a vector of 5 floats, then a matrix of 3 * 3 integers:

In [18]:
vec = np.array ([ 3.32 , 5.67 , 1.11 , 9.81 , 13.41 ])
vec

array([ 3.32,  5.67,  1.11,  9.81, 13.41])

In [19]:
 my_arr = np.array ([[ 0 , 1 , 2 ], [ 3 , 4 , 5 ], [ 6 , 7 , 8 ]]) # each listprovided becomes a row of the matrix

In [20]:
summarray(my_arr)

The array has 2 dimension (s), its shape is (3, 3) ,            its size is9 (ie it contains 9 elements in total) and its            dtype is int64.


### Creating an array and adding vianumpy.append ().

We can also start from an array, whether empty or not, and then add new ones elements via the use of the functionumpy.append ():

In [23]:
 my_arr = np.array ([])
for i in range ( 0 , 10 ): # upper bound excluded
    my_arr = np.append (my_arr, i) 
    my_arr

In [24]:
my_arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

It is important to note that quenumpy.append () does not have a place-place- this means that the values provided are added to a copy of the initial array, and it is this enriched copy that returns the function.

In the case of a multidimensional array, it is possible to use the optionnelaxelax arguments axis = None (which is the case by default, and so in the example above), numpy.append () returns a flattened array.

### Creating an Array Using NumPy Functions

Let's continue to create arrays but now using dedicated NumPy functions:

In [25]:
 # Creation of vectors of 10 identical values, 0 or 1 2 
np.ones ( 10 ) # with ones 3  
np.zeros ( 10 ) # with zeros 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.arange ( 0 , 50 , 5 , dtype = float ) 

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [27]:
 # Creation of a vector of 10 uniformly distributed values ​​between start and stop 2  
np.linspace (start = 0. , stop = 1. , num = 10 , endpoint = False ) 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [30]:
 # Creating a matrix of 10 by 10 values
my_mat_0 = np.zeros (( 10 , 10 )) # with zeros 3  
my_mat_0

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
my_mat_1 = np.ones ( ( 10 , 10 )) # with some 4  
my_mat_1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
# Let's check the form and type of my_mat_1   
summarray (my_mat_1) 

The array has 2 dimension (s), its shape is (10, 10) ,
            its size is100 (ie it contains 100 elements in total) and its 
            dtype is float64.


In [34]:
# Warning, empty does not always return an array with values ​​initialized to zero 
np.empty ([ 10 ])

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## Converting from one type to another

Finally, let's see how to convert an array from undtypevers to another - in this case from int to float:

In [35]:
my_arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
my_arr_float = my_arr.astype (np.float64)
my_arr_float 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
summarray (my_arr)

The array has 1 dimension (s), its shape is (10,) ,
            its size is10 (ie it contains 10 elements in total) and its 
            dtype is float64.


In [38]:
summarray (my_arr_float) 

The array has 1 dimension (s), its shape is (10,) ,
            its size is10 (ie it contains 10 elements in total) and its 
            dtype is float64.


# Arithmetic and comparisons with NumPy arrays

## Vector operations

As mentioned, one of the advantages of NumPy arrays is to allow operations to be performed

and calculations enbatch in a vector way, and therefore without having to use a loop (which allows in

general to shorten the calculation time).

Any arithmetic operation on arrays of the same size is applied element by element

(element-wise):

In [39]:
my_arr = np.array ([[ 1. , 2. , 3. ], [ 4. , 5. , 6. ]])
my_arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
# Multiplication of the array by itself (ie squared) 2  
my_arr * my_arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [42]:
# Subtraction 2  
my_arr - my_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

##  Operations with scalars

In the case of an arithmetic operation involving a number (English scalar), the so-called operation and number will be applied to each element composing the array:


In [43]:
my_arr * 10

array([[10., 20., 30.],
       [40., 50., 60.]])

In [44]:
my_arr - 3

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

## Powers and square roots

NumPy offers functions dedicated to powers (numpy.square () andnumpy.power ()) as well than square roots (numpy.sqrt ()):


In [45]:
np.square (my_arr) #

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [46]:
np.power (my_arr, 3 ) 

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [47]:
np.sqrt (my_arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# Generating random numbers with NumPy

NumPy allows thanks to its modulenumpy.randomde generate arrays of random numbers of efficient way - several functions are available depending on the desired source distribution (see the [official documentation](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html)).

## Method

For example, let's generate an array of 25 (5 * 5) samples from the standard normal distribution


In [48]:
np.random.normal (size = ( 5 , 5 ))

array([[-0.63183658,  0.78837298, -0.0457775 , -1.55442529,  0.69098968],
       [ 0.90490992,  0.32619503, -1.7422548 ,  0.59160798,  1.27111669],
       [-0.90369057,  0.59396487,  0.58079807,  0.65818372, -0.31137084],
       [-0.04475622, -0.52835547, -1.74848785,  0.45994542,  0.96981571],
       [ 0.59799273,  0.53475658, -0.57555766, -0.6658237 ,  0.56425924]])

Re-executing the cell code above will result in 25 new samples, which
confirms that this is a random draw - or rather pseudo-random to be more precise.

Indeed, these so-calledaluminant numbers are generated by a deterministic algorithm.

based on what is called a seed (English ouseeden). So, a random number generator

can be made deterministic (and its reproducible prints) simply by defining the seed at, preliminary:

In [49]:
np.random.seed ( 123 )
np.random.normal (size = ( 5 , 5 )) 

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025],
       [ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ],
       [-0.67888615, -0.09470897,  1.49138963, -0.638902  , -0.44398196],
       [-0.43435128,  2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904, -1.25388067]])

Re-executing the cell code above will this time remove the same 25 samples,

because we have defined the seed beforehand - try!

If we generate 25 samples again, they will be different - let's do the 2 more times:

In [50]:
[np.random.normal (size = ( 5 , 5 )) for i in range ( 2 )] 

[array([[-0.6377515 ,  0.9071052 , -1.4286807 , -0.14006872, -0.8617549 ],
        [-0.25561937, -2.79858911, -1.7715331 , -0.69987723,  0.92746243],
        [-0.17363568,  0.00284592,  0.68822271, -0.87953634,  0.28362732],
        [-0.80536652, -1.72766949, -0.39089979,  0.57380586,  0.33858905],
        [-0.01183049,  2.39236527,  0.41291216,  0.97873601,  2.23814334]]),
 array([[-1.29408532, -1.03878821,  1.74371223, -0.79806274,  0.02968323],
        [ 1.06931597,  0.89070639,  1.75488618,  1.49564414,  1.06939267],
        [-0.77270871,  0.79486267,  0.31427199, -1.32626546,  1.41729905],
        [ 0.80723653,  0.04549008, -0.23309206, -1.19830114,  0.19952407],
        [ 0.46843912, -0.83115498,  1.16220405, -1.09720305, -2.12310035]])]

On the other hand, if we redefine the seed and then re-generate 3 times 25 random numbers:

In [51]:
np.random.seed ( 123 )
[np.random.normal (size = ( 5 , 5 )) for i in range ( 3 )]

[array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025],
        [ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ],
        [-0.67888615, -0.09470897,  1.49138963, -0.638902  , -0.44398196],
        [-0.43435128,  2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
        [ 0.73736858,  1.49073203, -0.93583387,  1.17582904, -1.25388067]]),
 array([[-0.6377515 ,  0.9071052 , -1.4286807 , -0.14006872, -0.8617549 ],
        [-0.25561937, -2.79858911, -1.7715331 , -0.69987723,  0.92746243],
        [-0.17363568,  0.00284592,  0.68822271, -0.87953634,  0.28362732],
        [-0.80536652, -1.72766949, -0.39089979,  0.57380586,  0.33858905],
        [-0.01183049,  2.39236527,  0.41291216,  0.97873601,  2.23814334]]),
 array([[-1.29408532, -1.03878821,  1.74371223, -0.79806274,  0.02968323],
        [ 1.06931597,  0.89070639,  1.75488618,  1.49564414,  1.06939267],
        [-0.77270871,  0.79486267,  0.31427199, -1.32626546,  1.41729905],
        [ 0.80723653,

We find our 3 prints made above - the behavior of the number generator

pseudo-random is therefore very deterministic.

Defining the seed allows us to have reproducible prints afterwards, much like

if it repositioned us in the same place in a pre-determined sequence.

## Method

A second approach is to define the seed in isolation (and not globally).

as is the case withrandom.seed ()), by instantiating aRandomState object:

In [52]:
rand_gen = np.random.RandomState (seed = 123 )
rand_gen.normal (size = ( 5 , 5 )) 

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025],
       [ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ],
       [-0.67888615, -0.09470897,  1.49138963, -0.638902  , -0.44398196],
       [-0.43435128,  2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904, -1.25388067]])

As you can see, this 2nd method generates the same random numbers if it is

provides the same seed. For confirmation re-generate 2 more times 25 normal samples:

In [54]:
[rand_gen.normal (size = ( 5 , 5 )) for i in range ( 2 )] 

[array([[ 1.03972709, -0.40336604, -0.12602959, -0.83751672, -1.60596276],
        [ 1.25523737, -0.68886898,  1.66095249,  0.80730819, -0.31475815],
        [-1.0859024 , -0.73246199, -1.21252313,  2.08711336,  0.16444123],
        [ 1.15020554, -1.26735205,  0.18103513,  1.17786194, -0.33501076],
        [ 1.03111446, -1.08456791, -1.36347154,  0.37940061, -0.37917643]]),
 array([[ 0.64205469, -1.97788793,  0.71226464,  2.59830393, -0.02462598],
        [ 0.03414213,  0.17954948, -1.86197571,  0.42614664, -1.60540974],
        [-0.4276796 ,  1.24286955, -0.73521696,  0.50124899,  1.01273905],
        [ 0.27874086, -1.37094847, -0.33247528,  1.95941134, -2.02504576],
        [-0.27578601, -0.55210807,  0.12074736,  0.74821562,  1.60869097]])]

We get the same sequence as before.

# Indexing and assignment

## Reminders

To begin, let's remember how we index a Python list:

In [56]:
my_list = [ 0 , 1 , 2 , 3 , 4 ]
my_list

[0, 1, 2, 3, 4]

In [57]:
my_list [ 0 ] # returns the 1st value

0

In [58]:
my_list [ - 1 ] # returns the last value - identical to my_list [4]

4

## Lists to vectors

The assignment and indexing of NumPy arrays is based on similar - or even identical - principles

in the case of vectors (ie one-dimensional arrays, like a Python list):

In [59]:
my_vec = np.linspace ( - 10 , 10 , 20 )
my_vec 

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [60]:
my_vec [ 3 ]

-6.842105263157895

In [61]:
my_vec [ 0 : 2 ] # slicing (upper bound excluded)

array([-10.        ,  -8.94736842])

## Multidimensional generalization

These same principles are generalized in NumPy to multidimensional data structures.

A vector with 1 single dimension, a 2 dimensional matrix (lines, axis = 0 and columns, axis = 1) ...

Thus, the basic principle of indexing and assignment is, for an array of n dimensions:

array [idx dim 1, idx dim 2, ..., idx dim n]

If we apply this generalized principle to the particular case of a matrix (ie 2 dimensions), this gives:

array [idx lines idx column]

In other words, the first dimension (axis = 0) always corresponds to lines and the second dimension (axis

= 1) to the columns, cf. this illustration by Wes McKinney:

Source: Python for Data Analysis (2nd Ed.), Chapter 4

5.4 Examples of indexing and assignment

FIGURE 6

In [62]:
my_arr = np.array ([np.arange ( 0 , 5 ),
                     np.arange ( 5 , 10 ),
                     np.arange ( 10 , 15 ),
                     np.arange ( 15 , 20 )])
my_arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
my_arr [ 2 , 2 ]

12

In [64]:
 # Indexing - recovery of the 3rd line 2 
my_arr [ 2 ]

array([10, 11, 12, 13, 14])

# Indexing - recovery of the 2nd column 2

In [65]:
my_arr [:, 1 ] 

array([ 1,  6, 11, 16])

: means "all values", more precisely here "all lines" because it is in first

position (dimension 1, soaxis = 0).

 # Slicing - recovery of the first 2 lines 2

In [66]:
my_arr [: 2 ]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Axes

Finally, before switching to NumPy functions, it is important to return to the concept of axes (ie

axis = 0, axis = 1 ...) - below applied to a matrix:

FIGURE 7

Source: StackOverflow

-Axis = 0-> lines; think from top to bottom; calculating the sum (or average ...) the lines longdes

(across / alongrows), ie by column.

-Axis = 1-> columns; think from left to right; calculating the sum (or average ...) along

columns (across / alongcolumns), ie per line.

# Some functions to know

## NumPy

Let's start with some particularly useful NumPy features, some of which have already been

discussed above concerning the creation of arrays:

Click on the name of the function to consult the official documentation.

### numpy.arange ()

Returns an array of values ​​distributed within the intervallestart, stop (stop excluded),

with the possibility of defining a step (step = 1 by default).

numpy.arange (start, stop, step, dtype = None )

Equivalent derange () in pure Python, but returns an array instead of a list.

In [67]:
np.arange ( 0 , 10 , 2 )

array([0, 2, 4, 6, 8])

### numpy.linspace ()

Returns an array of uniformly distributed values ​​within the intervallestart, stop. The

bornestopp can be excluded if needed (it is included by default).

In [69]:
np.linspace ( - 1 , 1 , num = 10 , endpoint = True )

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

### numpy.repeat ()

Returns an array composed of two times.

numpy.repeat (a, repeats, axis = None )

The argumentaxisis optional and allows to specify on which axis to repeat the values. By default,

axis = None, which flattens the input and output array.

In [70]:
np.repeat ( 7 , 10 )

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [71]:
vec = np.array ([ 1 , 2 , 3 ])
np.repeat (vec, 10 )

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3])

### numpy.unique ()

Returns the unique values ​​of the array (ie filters the redundant values).

numpy.unique (ar, return_index = False , return_inverse = False ,
return_counts = False , axis = None )

Here again, the argument optionnelaxispermet to specify the axis on which to intervene. By default,

axis = None, which flattens the arrayar.

The other 3 arguments are optional and allow to return additional information.

tary, as the indices of unique elements. See help for more details.

In [72]:
vec = np.array ([ 1 , 2 , 3 , 1 , 2 , 3 , 1 ])
np.unique (vec)

array([1, 2, 3])

### numpy.ravel ().

Returns a copy of the reduced-size array (ie a vector).

The flatten () method can also be used:

In [75]:
my_arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
my_arr2 = my_arr.flatten () # also returns a vector

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]  \ n \ n Shape = (20,)


### numpy.sum ()

Returns the sum of the elements of the array along a given axis (axis = 0 or 1 ...).

numpy. sum (a, axis = None , dtype = None )

By default, axis = None, which will calculate the sum of all the elements of the array (ie of the array

"Flattened", ouflattened in English).

In [ ]:
 vec = np.array ([ 0 , 1 , 2 , 3 , 4 ])
2  np. sum (vec) # sum of all the elements of the vector 3 10

 my_arr = np.array ([vec, 2 * vec, 3 * vec])
2  my_arr 3 array ([[ 0 , 1 , 2 , 3 , 4 ], 4 [ 0 , 2 , 4 , 6 , 8 ], 5 [ 0 , 3 , 6 , 9 , 12 ]])


In [ ]:

 np. sum (my_arr) # axis = None -> sum of all elements of
array
2 60

 np. sum (my_arr [ 1 ]) # sum of the second line
2 20

 np. sum (my_arr, axis = 0 ) # axis = 0 -> sum of lines (across rows)
by column
2 array ([ 0 , 6 , 12 , 18 , 24 ])

 np. sum (my_arr, axis = 1 ) # axis = 1 -> sum of columns (across
columns) per line
2 array ([ 10 , 20 , 30 ])

 np. sum ([]) # unsurprisingly, the sum of an empty array is 0.0
2 0.0

### numpy.dot ()

Calculates Ledot productde 2 arrays.

numpy.dot (a, b)

The behavior denumpy.dot () depends on the form of the provided arrays, so refer to

help for more information.

Note that since Python 3.5 it is possible to use the symbol @ to calculate the product of 2 matrices

or a matrix and a vector:

# Check

If we use only the condition argument, then numpy.where () returns the corresponding indexes

to the values ​​of the array satisfying the condition:

np.where (vec1 > 40 )
2 (array ([ 5 , 6 , 7 , 8 , 9 ], dtype = int64),)

### numpy.concatenate ()

Merges a sequence of arrays along a particular axis:

numpy.concatenate ((a1, a2, ...), axis = 0 )

Defaultaxis = 0; siaxis = None, then the arrays will be flattened beforehand and

merged into a single vector (ie a dimension).

In [76]:
my_arr1 = np.array ([[ 0 , 0 , 0 ], [ 1 , 1 , 1 ]])
my_arr1


my_arr2 = np.array ([[ 2 , 2 , 2 ], [ 3 , 3 , 3 ]])
my_arr2




array([[2, 2, 2],
       [3, 3, 3]])

In [77]:
np.concatenate ((my_arr1, my_arr2), axis = 0 )




array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [78]:
np.concatenate ((my_arr1, my_arr2), axis = 1 ) # axis = 1 ->




array([[0, 0, 0, 2, 2, 2],
       [1, 1, 1, 3, 3, 3]])

In [79]:
np.concatenate ((my_arr1, my_arr2), axis = None ) # axis = None -> arrays

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

NumPy also offers the functions numpy.vstack () and numpy.hstack () to assemble

arrays vertically and horizontally (respectively).

### numpy.reshape ()

Modifies the shape of an array without changing the data it contains.

numpy.reshape (a, newshape)

In [80]:
my_arr = np.arange ( 6 )



In [81]:
np.reshape (my_arr, ( 3 , 2 )) # equivalent to my_arr.reshape ((3, 2))




array([[0, 1],
       [2, 3],
       [4, 5]])

In [82]:
np.reshape (my_arr, ( 2 , 3 )) # equivalent to my_arr.reshape ((2, 3))


array([[0, 1, 2],
       [3, 4, 5]])

### numpy.transpose ().

Swap the dimensions of an array.

numpy.transpose (a, axes = None )

Defaultaxes = Nonece that reverses the dimensions; otherwise the function swaps the axes

according to the values ​​provided via this argument.

In [84]:
my_arr = np.arange ( 8 ) .reshape (( 4 , 2 ))
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [87]:
my_arr = np.transpose (my_arr)
my_arr

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [88]:
my_arr = np.transpose (my_arr, ( 1 , 0 ))
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])